### ISSUE TITLE
使用するライブラリを調査

### ISSUE THREAD

**Issue by a1bin0** [a1bin0/MotionCaptureAudio#1]
- [x] openNIとキネクトSDKの違い
- [x] PCLの機能を調査し利用するか検討

**Comment by mae0003** [comment]
**Kinect for Windows SDK ベータ 2 と OpenNI の比較**
http://www.atmarkit.co.jp/fdotnet/special/comparekinect02/comparekinect02_01.html

**Comment by morir** [comment]
PCLには、フィルタリング、特徴推定、サーフェス再構成、レジストレーション（位置合わせ）、モデルフィッティング、セグメンテーションなど、たくさんの最先端のアルゴリズムが含まれています。

http://derivecv.tumblr.com/post/10198738207

**Comment by a1bin0** [comment]
PCLは3D点群のライブラリである。
openNIで機能に不足を感じたら利用を検討する。
