### ISSUE TITLE
シーケンス図の作成

### ISSUE THREAD

**Issue by a1bin0** [a1bin0/MotionCaptureAudio#12]
- [x] 再生シーケンス図の作成
- [x] 停止シーケンス図の作成
- [x] 音量調整シーケンス図の作成
- [x] レビュー

**Comment by a1bin0** [comment]
https://docs.google.com/file/d/0By0QhKSWO-96ZmtrcHMxQ2x5NFE/edit

**Comment by morir** [comment]
11/20　進捗：再生のみ完了

**Comment by morir** [comment]
11/27　進捗なし。発表用資料でもつかうので、次週までにまとめる！
