### ISSUE TITLE
開発環境の作成

### ISSUE THREAD

**Issue by mae0003** [a1bin0/MotionCaptureAudio#2]
- [x] VisualStudio2013 のインストール  
- [x] Sensor (XTIONドライバ) のインストール
- [x] NiTE のインストール
- [x] インストール手順の作成

**Comment by a1bin0** [comment]
7月17日にインストールします。

**Comment by mae0003** [comment]
7/16 未実施 :anger:

**Comment by a1bin0** [comment]
openNI ver1.5.4.0、sensor ver5.1.2.1、NiTE ver1.5.2.21をインストールしました
センサーデバイスは動作しています

**Comment by mae0003** [comment]
どうやって確認したのー？

**Comment by a1bin0** [comment]
https://simple-openni.googlecode.com/files/OpenNI_NITE_Installer-win32-0.27.zip
のファイルを解凍し
openni-win32-1.5.4.0-dev⇒sensor-win32-5.1.2.1-redist⇒nite-win32-1.5.2.21-dev
の順にインストールしました

**Comment by a1bin0** [comment]
センサーデバイスの動作確認について
openNI⇒samples⇒binにあるSimpleViewer.exeを起動しました
こちらのシルエットを認識し、背景を黒、シルエットを黄色で描画する画面が表示されます

**Comment by mae0003** [comment]
ほほーほほほー
よかったねー
でかした。

**Comment by mae0003** [comment]
OPEN NI も NITE も 64 bit 版 があるみたいだよ
OpenNI-Windows-x64-2.2.0.33
NiTE-Windows-x64-2.2

http://structure.io/openni 
けど ここに↑ OPEN NI はあった

**Comment by a1bin0** [comment]
SimpleViewer.exe実行中のキャプチャです
センサーに近すぎると認識されないようです
http://i.imgur.com/piIaH7O.jpg

資料ありがとうございます

**Comment by mae0003** [comment]
64bit のほうがバージョンも新しいから試してみたら！
がんばれ

**Comment by a1bin0** [comment]
残念ながら環境が32bitです
•OpenNI 2.2.0.33 Beta (x86) 8.2mb, zippedダウンロードしました

**Comment by mae0003** [comment]
あれ？ ASUS の PC WIN8 32 bit なの？
64 bit だと思い込んでた

**Comment by a1bin0** [comment]
ASUS TransBook T100TA-DK32Gってのを使ってます
win8.1の32bitです

**Comment by mae0003** [comment]
そっか！了解

**Comment by a1bin0** [comment]
OpenNI 2.2.0.33 Beta (x86) をインストールしました
Program Files\OpenNI2\Samples\BinのSimpleViewer.exeを起動し、ver1.5.4と同様の動作を確認しました
これよりNITEの動作確認に取り掛かります

**Comment by a1bin0** [comment]
NITEも動くようです
Program Files\OpenNI\Samples\Bin\Release\NiViewer.exeを起動中に
Program Files\PrimeSense\NITE\Samples\Bin\Release\Sample-CircleControl.exeを実行すると
カメラに最も近い点の軌跡を白線で描画してくれます
その他のサンプルも動作を確認しました

**Comment by a1bin0** [comment]
リラックマを回転させた時のキャプチャです
http://i.imgur.com/HCbd6BN.jpg

**Comment by mae0003** [comment]
手順書は Wiki ってとこで書いてまとめておくと いいと 思うよ
参考に書いてみたからみてみて
