### ISSUE TITLE
Exion Pro Live を山内君から

### ISSUE THREAD

**Issue by mae0003** [a1bin0/MotionCaptureAudio#3]
- [x] メール
- [x] 引き取り

**Comment by a1bin0** [comment]
山内さん

お疲れ様です。
Xtion Pro LIVEをN1ソフト開発のためにお借りしたいと考えています。
7月10日、14日、15日のいずれかに、営業所へ受け取りに行ってもよろしいでしょうか？
都合の良い日時を教えてください。

営業所へうかがう時間帯は、18:30以降を予定しています。

佐藤
