### ISSUE TITLE
サンプルコード作成

### ISSUE THREAD

**Issue by a1bin0** [a1bin0/MotionCaptureAudio#6]
- [x] OpenNI ライブラリ参照設定 
- [x] NITEのライブラリ参照設定  
- [x] プロジェクトを作成し、Xtion から骨格データの取得する

**Comment by morir** [comment]
自前のプロジェクトを作成して、サンプルコードを取り込むメソッドを作る

**Comment by morir** [comment]
何がわからないか教えて～

**Comment by a1bin0** [comment]
OpenNI.Net.dllを参照してみました。
警告が出ているので調査します。追記：プロジェクトのプロパティを変更すれば警告されないようです。

構築されているプロジェクトのプロセッサ アーキテクチャ "MSIL" と、参照 "OpenNI.net, Version=1.5.4.0, Culture=neutral, PublicKeyToken=6b43d0c6cf74ee7f, processorArchitecture=x86" のプロセッサ アーキテクチャ "x86" の間には不一致がありました。この不一致は、ランタイム エラーを発生させる可能性があります。プロジェクトと参照の間でプロセッサ アーキテクチャが一致するように、構成マネージャーを使用してターゲットとするプロジェクトのプロセッサ アーキテクチャを変更するか、ターゲットとするプロジェクトのプロセッサ アーキテクチャに一致するプロジェクト アーキテクチャとの依存関係を参照で設定することを検討してください。

**Comment by a1bin0** [comment]
OpenNIをインストール時の付属フォルダー内の、サンプルプログラム（明るさの取得）のビルドが通ることを確認しました。
テキスト(OpenNIの本)で取り扱っているコードはC++用。

**Comment by morir** [comment]
↓かおるんさんがWaveジェスチャーのサンプル載せてくれてるね。
http://d.hatena.ne.jp/kaorun55/20111214/1323912711

↓Vangosさんが作成したOpenNIのみで動作するWaveジェスチャーを認識するサンプルプログラムらしいよ。
https://groups.google.com/forum/#!topic/openni-dev/8K1nEj8rzyI

**Comment by a1bin0** [comment]
http://d.hatena.ne.jp/kaorun55/20111214/1323912711
のWave（手を左右に振る動作を認識）を試行中です。ビルドは通りました。

セッションマネージャの作成＝NITEの初期化の部分で中断してしまいます。
SessionManager sessionManager = new SessionManager(context, "Wave", "RaiseHand");
↑の行で中断してしまいます、エラーメッセージを以下にペーストします。

型 'OpenNI.StatusException' のハンドルされていない例外が OpenNI.Net.dll で発生しました
追加情報:No hand generator found. One is needed for session manager.

**Comment by a1bin0** [comment]
NITEの初期化までできました。カメラとの距離感が問題だったのだと考えています。
Xtionから1メートルほど離れて手を動かすとstatic void sessionManager_SessionStartメソッド内のコンソールが作動しました。

NITEを初期化して10秒ほど経過するとcontext.WaitAndUpdateAll();で処理が中断する現象が発生しています。
以下にエラーメッセージをペーストします。
型 'OpenNI.StatusException' のハンドルされていない例外が OpenNI.Net.dll で発生しました
追加情報:A timeout has occurred when waiting for new data!

**Comment by a1bin0** [comment]
手持ちのSamplesConfig.XmlではOpenNIがうまく初期化できていなかったようなので、https://github.com/kaorun55/openni_sandbox/blob/master/OpenNI_Advent_Calendar_2011/HelloOpenNI/SamplesConfig.xmlのファイルを使用してみました。
すると、Audioのノードが作成できないというエラーが発生し、OpenNI初期化の段階でフリーズします。

ビルド時には「同じ依存アセンブリの異なるバージョンで競合が見つかりました」と警告が出ます。
出力で「競合を解決して警告を消去するために、app.config でアセンブリ "OpenNI.Net, Culture=neutral, PublicKeyToken=6b43d0c6cf74ee7f" をバージョン "1.5.2.23" [] からバージョン "1.5.4.0" [C:\Program Files\OpenNI\Bin\OpenNI.Net.dll] にマップし直してください。」と表示されますが、設定の方法がわかりません。

**Comment by a1bin0** [comment]
WAVE動作を読ませ、NITEの初期化し、セッション開始のコンソール出力を確認しました。
セッションマネージャー更新のタイミングが悪いらしく、WAVE動作は今のところ初期化時の1度きりしか読み取れていないようです。

**Comment by mae0003** [comment]
マニュアルよく読んで、サンプルコードよく見て水曜日までに前進したまえ。

**Comment by a1bin0** [comment]
手振りを認識させ、コンソールに出力できるようになりました。
OpenNIを断続的に初期化しているメソッド内でNITEの更新処理を行い、クラスにSessionManagerを持たせて解決しました。
ようやくスタートラインです。明日、機材一式を持ってきます。
