### ISSUE TITLE
base.NET 調査

### ISSUE THREAD

**Issue by mae0003** [a1bin0/MotionCaptureAudio#8]
- [x] インストール手順
- [x] MP3 再生のサンプル作成

**Comment by a1bin0** [comment]
BASSはインストール済みですが、アドオンの違いがよくわからないので調査中です

**Comment by a1bin0** [comment]
MP3以外のフォーマットが扱いやすいかもしれないので、使い勝手のいい形式を探してみます

**Comment by mae0003** [comment]
アドオンの違いって何？

**Comment by mae0003** [comment]
http://bass.radio42.com/help/

**Comment by morir** [comment]
VS2013に32ビット用mp3-freeのbass.dllを参照させたら再生できました。
mp3以外にも、wave、oggも再生可能でした。

ただ、一時停止がうまく機能しないです。。。

**Comment by morir** [comment]
一時停止できました。　←原因は初歩的なコーディングミスです。。
また、exeを複数起動してそれぞれで別の音楽ファイルを同時に再生できました。

Volume調整も確認しました。

＞佐藤くん
上記で使った自作のサンプルコードをFutureClimbingに置きました。
→森のキャビネット＞N1＞BassサンプルにBassSample.zipファイルがあると思うので、
　　必要に応じてダウンロードしてみてください。

**Comment by a1bin0** [comment]
サンプルプログラムありがたくいだたきました
このＰＣの環境でも再生・停止が可能でした

**Comment by morir** [comment]
Bass.dllについてインストール手順に追加したらこのIssueはCloseでOK！

**Comment by morir** [comment]
今週中に絶対やる！
