### ISSUE TITLE
ユースケース作成

### ISSUE THREAD

**Issue by morir** [a1bin0/MotionCaptureAudio#9]
- [x] 再生する
- [x] 停止する
- [x] 音量を調節する

**Comment by a1bin0** [comment]
ユースケース図のリンクを張ります
再生
https://drive.google.com/open?id=0By0QhKSWO-96UEQyY3k1Uldybjg&authuser=0
停止
https://drive.google.com/open?id=0By0QhKSWO-96Q1Q2QkZyaVI2Qzg&authuser=0
音量調節
https://drive.google.com/open?id=0By0QhKSWO-96YnJGRmllTUdqZFk&authuser=0
